pepew_status/urls.py
from django.conf.urls import url

from .views import add_status, index, profile

app_name='pepew_status'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-status/$', add_status, name='add_status'),
    url(r'^profile/$', profile, name='profile'),
]

test_of_pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include('pepew_status.urls', namespace='status')),
    url(r'^$', RedirectView.as_view(url='/status/')),
    url(r'^profile/', RedirectView.as_view(url='/status/profile/'))
]

pepew_status/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Status(models.Model):
    status = models.CharField(max_length=300,
                              validators=[MaxLengthValidator(300)])
    created_at = models.DateTimeField(auto_now_add=True)

pepew_status/forms.py
from django import forms

from .models import Status


class StatusForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)

        self.fields['status'].label = 'Status'
        self.fields['status'].widget = forms.Textarea(attrs={'class': 'form-control',
                                                             'placeholder': 'Masukkan status Anda.',
                                                             'rows': 5,
                                                             'cols': 8}
                                                      )
        self.fields['status'].error_messages = {'max_length': 'Status tidak boleh melebihi 300 karakter.',
                                                'required': 'Status harus diisi.'}

    class Meta:
        model = Status
        fields = ['status']

pepew_status/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import StatusForm
from .models import Status


def index(request):
    status = Status.objects.all()
    form = StatusForm()
    html = 'index.html'
    return render(request, html, {'status': status, 'form': StatusForm})


def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('status:index'))
    else:
        form = StatusForm()
    return render(request, 'index.html', {'form': form,
                                          'status': Status.objects.all()})


def profile(request):
    return render(request, 'profile.html')

pepew_status/templates/index.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block content %}
        <div class="main-div" style="color:black">
            <div class="jumbotron">
                <div class="container-fluid">
                    <h1 class="page-header" style='color:black'>Hello apa kabar?</h1>
                </div>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block" action="{% url 'status:add_status' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form }}
                    </div>
                    <button id = 'hehe' type="submit" class="btn btn-primary">Input Status</button>
                </form>
            </div>

            <div id = 'container' class="container mx-auto d-block">
                {% if status %}
                    <table class="table table-hover table-striped table-dark" align="center" style="text-align: center">
                        <thead>
                            <tr>
                                <th scope="col">Status</th>
                                <th scope="col">Waktu Pembuatan</th>
                            </tr>
                        </thead>
                        {% for data in status %}
                        <tr>
                            <td scope="row">{{ data.status }}</td>
                            <td scope="row">{{ data.created_at|date:"l" }}, {{ data.created_at }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                {% else %}
                    <h1 class="text-main">Tidak Ada Status</h1>
                {% endif %}
            </div>
        </div>
    {% endblock %}
</html>

pepew_status/templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="landing page">
        <meta name="author" content="Yaumi Alfadha - 1706023013">

        <title>
            {% block title %}
                Yaumi Alfadha - Index
            {% endblock title %}
        </title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/story_3.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Bitter|Chivo|Montserrat" rel="stylesheet">

    </head>

    <body>
        <header>
            {% include 'layout/header.html' %}
        </header>

        <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock content %}
        </content>

        <footer>
            {% include 'layout/footer.html' %}
        </footer>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

pepew_status/templates/layout/footer.html
<!DOCTYPE html>
<html lang="en">
        <div class="border-line-main"></div>
        <div class="row contacts">
            
        </div>
</html>

pepew_status/templates/layout/header.html
<!DOCTYPE html>
<html lang="en">
    <nav class="navbar navbar-expand-lg main-navbar">
        <a class="navbar-brand navbar-button" href="{% url 'status:index' %}">Home</a>
        <a class="navbar-brand navbar-button" href="{% url 'status:profile' %}">Profile</a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</html>

pepew_status/templates/profile.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Yaumi Alfadha - About
    {% endblock title %}

    {% block content %}
        <div class="main-div">
            <div class="image-div">
                <img class="mx-auto d-block avatar-image" src="https://preview.ibb.co/gCZLop/self.jpg">
            </div>

            <div>
                <h1 class="text-main">Tentang saya</h1>
            </div>

            <div class="bio-desc mx-auto d-block">
                <h4 class="text-sub">Yaumi Alfadha</h4>
                <h4 class="text-sub">Jakarta</h4>
                <h4 class="text-sub">Web Developer</h4>
            </div>

            <div class="border-line-main"></div>

            <div>
                <h1 class="academic-text">Academic History</h1>
            </div>

            <div class="container mx-auto d-block academic-div">
                <div class="row">
                    <div class="col">
                        <a class="ui-logo academic-logo" title="ui-logo"></a>
                    </div>
                    <div class="col academic-desc">
                        <p>Universitas Indonesia</p>
                        <p>Computer Science Major</p>
                        <p>2017 - Current</p>
                    </div>
                </div>
            </div>



            <div class="border-line-main"></div>

            <div>
                <h1 class="work-text">Work Experience</h1>
            </div>

            <div class="container mx-auto d-block project-div">
                <div class="row">
                    <div class="col">
                        <a class="fuki-logo project-logo" title="fuki-logo"></a>
                    </div>
                    <div class="col project-desc">
                        <p>FUKI Fasilkom UI 2018</p>
                        <p>Penjagaan Aset FUKI</p>
                    </div>
                </div>
            </div>

            <div class="border-line-main"></div>

            <div class="container mx-auto d-block skill-div">
                <h1>Skills</h1>
            </div>

            <div class="container skill-logo-div" style="margin-bottom: 20px;">
                <div class="row">
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/java.png' %}" width="200px" height="200px" alt="java-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/python.png' %}" width="200px" height="200px" alt="python-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/HTML5_Badge_256.png' %}" width="200px" height="200px" alt="html-logo">
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</html>